require('dotenv').config();
const mongoose = require('mongoose');
const FAQ = require('../models/FAQ');

const faqs = [
  // ABOUT
  { category: 'About', sectionId: '1.1', question: 'What is the Vicharanashala internship?', answer: 'A two-month internship run by Vicharanashala, a research lab at IIT Ropar. You will work on a real open-source project under a mentor, after a short training phase tailored to where you already are. The internship is free — we do not charge, and the work is real.', tags: ['about', 'overview', 'vicharanashala', 'iit ropar'], keywords: ['internship', 'what', 'vicharanashala', 'overview'], importance: 'high', verified: true, source: 'official' },
  { category: 'About', sectionId: '1.2', question: 'What is VINS?', answer: 'VINS is the Vicharanashala Internship — an online programme open to anyone who clears our interview. The work is real open-source contribution under a mentor, the certificate is from the Vicharanashala Lab for Education Design at IIT Ropar, and the programme itself is free (we charge nothing). There is no stipend. If you are seeing a yellow VINS panel on your result page, you are selected.', tags: ['vins', 'online', 'selected', 'stipend'], keywords: ['vins', 'selected', 'online', 'programme', 'free'], importance: 'critical', verified: true, source: 'official' },
  { category: 'About', sectionId: '1.3', question: 'What are the phases of VINS and what do the badges mean?', answer: 'VINS is structured as four phases: 🥉 Bronze (Phase 1) — short training period. 🥈 Silver (Phase 2) — main work, real open-source contribution. 🥇 Gold (Phase 3) — recognition for standout contributions. 🏆 Platinum (Phase 4) — standing invitation to visit the lab. Most interns finish at Bronze + Silver, and that is exactly what the certificate is for.', tags: ['phases', 'bronze', 'silver', 'gold', 'platinum', 'badge'], keywords: ['phase', 'badge', 'bronze', 'silver', 'gold', 'platinum'], importance: 'high', verified: true, source: 'official' },
  { category: 'About', sectionId: '1.4', question: 'Who is the internship for? Are alumni eligible?', answer: 'The internship is for currently-enrolled students at any college or university — undergraduate, postgraduate, or doctoral. Candidates who have already graduated and are not currently enrolled in any programme are not eligible for this cycle.', tags: ['eligibility', 'alumni', 'students', 'enrolled'], keywords: ['eligible', 'student', 'alumni', 'enrolled', 'graduate'], importance: 'high', verified: true, source: 'official' },
  { category: 'About', sectionId: '1.6', question: 'Can I take leave during the internship for my class or exam?', answer: 'Leave is not permitted. If you are also attending classes or exams, you will be relieved from the internship immediately and will need to join the next batch when it starts. VINS requires full attention — 6 to 10 hours a day.', tags: ['leave', 'exam', 'class', 'attendance'], keywords: ['leave', 'exam', 'class', 'attendance', 'permitted'], importance: 'critical', verified: true, source: 'official' },
  // TIMING
  { category: 'Timing', sectionId: '2.1', question: 'When can I start the internship?', answer: 'You can start any time in 2026, but your internship must finish by 31 December 2026. Start as soon as possible — cohort networking, TA support, and training are concentrated in the May-July window. Later starters will have lighter support and less cohort interaction.', tags: ['start', 'timing', 'cohort', 'deadline'], keywords: ['start', 'when', 'begin', 'timing', 'date', 'deadline'], importance: 'high', verified: true, source: 'official' },
  { category: 'Timing', sectionId: '2.2', question: 'How long is the internship?', answer: 'Two months from your chosen start date, with an optional one-month grace period if you need it. End must land on or before 31 December 2026.', tags: ['duration', 'length', 'months', 'grace'], keywords: ['how long', 'duration', 'months', 'weeks', 'grace period'], importance: 'high', verified: true, source: 'official' },
  { category: 'Timing', sectionId: '2.4', question: 'Can I start with the cohort and take a break during exams?', answer: 'No. VINS is a full-attention internship — 6 to 10 hours a day, sometimes more. Splitting that with college exams damages both sides. If your exams fall inside the cohort duration, defer your start to after your exams end. If discovered juggling both, the internship may be terminated.', tags: ['exams', 'break', 'juggle', 'full attention'], keywords: ['exam', 'break', 'pause', 'split', 'juggle'], importance: 'critical', verified: true, source: 'official' },
  // NOC
  { category: 'NOC', sectionId: '3.1', question: 'What dates do I put on the NOC?', answer: 'Default: your chosen start date → your start + 2 months (with up to 1 month grace), ensuring the end date is on or before 31 December 2026. Pick the earliest start date you can realistically make — the May–July summer window is the main cohort.', tags: ['noc', 'dates', 'format'], keywords: ['noc', 'dates', 'what dates', 'format', 'deadline'], importance: 'high', verified: true, source: 'official' },
  { category: 'NOC', sectionId: '3.2', question: 'Who can sign the NOC?', answer: 'Any authorised signatory at your college: HOD, Acting HOD (during holidays), Principal, Dean, Director, or Training & Placement Officer. For dual-degree students, either institution can sign. For IITM BS Online Degree students, any officer from the BS office can sign.', tags: ['noc', 'sign', 'hod', 'principal', 'authority'], keywords: ['who sign', 'noc', 'signatory', 'hod', 'principal', 'authority'], importance: 'high', verified: true, source: 'official' },
  { category: 'NOC', sectionId: '3.3', question: 'When do I submit the NOC? Is the deadline hard?', answer: 'The deadline is not hard — there is no specific cut-off date. But submit early to join the current summer cohort and get full mentor support. Later NOC submission means later start, lighter support.', tags: ['noc', 'deadline', 'submit', 'upload'], keywords: ['noc deadline', 'submit', 'when submit', 'upload'], importance: 'medium', verified: true, source: 'official' },
  { category: 'NOC', sectionId: '3.4', question: 'What format should I use for the NOC? Do I need to design it myself?', answer: 'No — use the printable NOC format provided on your samagama.in dashboard. Click "Download blank NOC", get it physically signed and stamped, scan it, and upload via "Upload signed NOC". You do not need college letterhead — the provided format is canonical.', tags: ['noc', 'format', 'template', 'download', 'upload'], keywords: ['noc format', 'template', 'design', 'download', 'letterhead'], importance: 'high', verified: true, source: 'official' },
  { category: 'NOC', sectionId: '3.5', question: 'What if my college gives me an NOC in their own format?', answer: 'A college\'s own NOC format is acceptable if all four required entries are present: (1) the signing authority\'s handwritten signature, (2) the signing authority\'s official email address, (3) your full name, and (4) your signature. If your college format lacks a signature field, sign anywhere prominently.', tags: ['noc', 'college format', 'custom', 'signature'], keywords: ['college format', 'own format', 'noc'], importance: 'medium', verified: true, source: 'official' },
  { category: 'NOC', sectionId: '3.6', question: 'Does the NOC need to be signed by hand? Are digital signatures accepted?', answer: 'Yes, handwritten signature is required along with the institutional rubber stamp/seal and the signatory\'s email address. Digital signatures are NOT accepted on the PDF path. If a physically-signed printout is impractical, use the email-forward path (§3.7).', tags: ['noc', 'digital signature', 'handwritten', 'physical'], keywords: ['digital signature', 'handwritten', 'physical sign', 'noc'], importance: 'high', verified: true, source: 'official' },
  { category: 'NOC', sectionId: '3.7', question: 'Can my HOD email the NOC instead of signing a printout?', answer: 'Yes — there is a fully-equivalent email-forward path. Download the text NOC from dashboard, fill in student-side fields, ask HOD to forward it from their official institutional email to sudarshan@iitrpr.ac.in with subject "NOC for my student [Your Full Name]". The forward counts as signature. Must come from official institutional email, not personal Gmail.', tags: ['noc', 'email', 'hod', 'forward', 'alternative'], keywords: ['email noc', 'hod email', 'forward', 'alternative'], importance: 'high', verified: true, source: 'official' },
  { category: 'NOC', sectionId: '3.9', question: 'What if my NOC is not formally verified yet?', answer: 'NOC verification takes 1 hour to 1 working day. If you need your offer letter sooner, upload a self-declaration on your profile — a tentative offer letter is issued immediately. The formal offer letter follows once NOC clears verification.', tags: ['noc', 'verification', 'pending', 'tentative', 'offer letter'], keywords: ['noc verification', 'pending', 'not verified', 'tentative'], importance: 'high', verified: true, source: 'official' },
  { category: 'NOC', sectionId: '3.10', question: 'My online course (Masai, NPTEL, Coursera) won\'t issue an NOC. What do I do?', answer: 'Online-only courses — Masai Institute, NPTEL/MOOC, Coursera, Udacity, bootcamps — do not by themselves make a candidate eligible. If you are concurrently enrolled in a full-time degree programme, obtain NOC from that college. If your only academic engagement is the online course, you are not eligible this cycle.', tags: ['masai', 'nptel', 'coursera', 'online', 'noc', 'eligible'], keywords: ['masai', 'nptel', 'online course', 'noc', 'eligible', 'coursera'], importance: 'critical', verified: true, source: 'official' },
  { category: 'NOC', sectionId: '3.12', question: 'Can Prof. Sudarshan Iyengar sign my NOC?', answer: 'No. Your NOC must be signed by an authorised signatory at the institution where you are enrolled as a student — HOD, Dean, Principal, or T&P Officer. Sudarshan Iyengar is faculty at IIT Ropar and cannot sign your NOC in a personal capacity.', tags: ['sudarshan', 'noc', 'faculty', 'sign'], keywords: ['sudarshan', 'professor', 'faculty sign', 'noc'], importance: 'medium', verified: true, source: 'official' },
  // OFFER LETTER
  { category: 'Offer Letter', sectionId: '4.1', question: 'How do I know I am selected?', answer: 'If you can see your yellow VINS result panel on samagama.in, you are selected. There is no separate selection step or confirmation email. The yellow panel IS your selection confirmation.', tags: ['selected', 'result', 'yellow panel', 'confirmation'], keywords: ['selected', 'how know', 'result', 'confirmation', 'yellow'], importance: 'critical', verified: true, source: 'official' },
  { category: 'Offer Letter', sectionId: '4.2', question: 'How do I opt into VINS?', answer: 'Tell Yaksha in the chat: "I want to take up the online internship without stipend." Yaksha will confirm. Opting in is the selection — no separate confirmation email is sent at that stage.', tags: ['opt in', 'yaksha', 'chat', 'accept'], keywords: ['opt in', 'how to join', 'accept', 'online internship'], importance: 'critical', verified: true, source: 'official' },
  { category: 'Offer Letter', sectionId: '4.3', question: 'When do I get the offer letter?', answer: 'Path 1 — Formal offer letter: issued once (a) your signed NOC is verified AND (b) you have confirmed internship dates on dashboard. Usually within 1 hour of both steps completing. Path 2 — Tentative offer letter: upload a self-declaration on your profile for immediate issuance. The offer letter lives on your samagama.in dashboard, not in email.', tags: ['offer letter', 'when', 'timeline', 'formal', 'tentative'], keywords: ['offer letter', 'when get', 'receive', 'download'], importance: 'critical', verified: true, source: 'official' },
  { category: 'Offer Letter', sectionId: '4.7', question: 'How do I accept the offer letter?', answer: 'Reply All on the offer-letter email thread. In the body, paste EXACTLY: "I, [Full Name], confirm that I have read, understood, and accepted all terms, conditions, and obligations set out in this offer letter and in the program FAQ at samagama.in. I formally accept the offer of Summer Internship 2026." Do not paraphrase, do not shorten, must reply within 5 days.', tags: ['accept', 'offer letter', 'reply', 'format', 'exact'], keywords: ['accept offer letter', 'how accept', 'reply format', 'acceptance'], importance: 'critical', verified: true, source: 'official' },
  { category: 'Offer Letter', sectionId: '4.8', question: 'What if I reply to the offer letter without using the exact acceptance format?', answer: 'The offer is withdrawn immediately with no further correspondence. This is deliberate — attention-to-detail is the first check. Non-compliant: paraphrasing, bare "I accept", missing date, missing FAQ-reference clause. If withdrawn, you can appeal via email to sudarshansudarshan@gmail.com with exact subject "Request to Reconsider: Confirmation Reply Error".', tags: ['withdrawal', 'offer letter', 'format', 'non-compliant', 'appeal'], keywords: ['wrong format', 'withdrawal', 'rejected', 'non-compliant', 'appeal'], importance: 'critical', verified: true, source: 'official' },
  { category: 'Offer Letter', sectionId: '4.16', question: 'Can I change my internship dates after the offer letter has been issued?', answer: 'Yes, but not via dashboard self-edit. The official from your institution who signed your NOC must email harshdeep.r@vicharanashala.ai (CC: sudarshan@iitrpr.ac.in) with subject "Date change request — [Your Full Name] — Vicharanashala Summership 2026". Student-sent requests cannot be processed at this stage.', tags: ['change dates', 'after offer letter', 'date change'], keywords: ['change dates', 'modify dates', 'after offer letter', 'new dates'], importance: 'high', verified: true, source: 'official' },
  // VIBE
  { category: 'ViBe', sectionId: '12.1', question: 'How do I log in to ViBe?', answer: 'Go to https://vibe.vicharanashala.ai/auth and sign up as a student with your registered email ID. Then: (1) Log in as student, (2) Check Notifications tab top right, (3) Accept the course invite for your MERN Course. Warning: logging in with a different email may result in missing course visibility.', tags: ['vibe', 'login', 'register', 'access'], keywords: ['vibe login', 'how login', 'sign up', 'register vibe'], importance: 'critical', verified: true, source: 'official' },
  { category: 'ViBe', sectionId: '12.2', question: 'I accepted the ViBe invite but it shows "No course enrolled". What do I do?', answer: 'Try: (1) Use correct registered email, (2) Check college email aliases, (3) Log out and back in, (4) Use personal wifi not college wifi. If still showing: Enable third-party cookies in Chrome (chrome://settings/cookies), add .vicharanashala.ai as exception. Change DNS to Google DNS: 8.8.8.8 and 8.8.4.4. Run ipconfig /flushdns in admin CMD.', tags: ['vibe', 'no course', 'enrolled', 'fix', 'cookies', 'dns'], keywords: ['no course enrolled', 'vibe not showing', 'course missing'], importance: 'high', verified: true, source: 'official' },
  { category: 'ViBe', sectionId: '12.3', question: 'Why are videos stuck or repeating on ViBe?', answer: 'This happens due to ViBe\'s monitored learning system. Common reasons: (1) Videos must be watched fully and in sequence — no skipping, (2) Camera and microphone permissions must be enabled, (3) Poor lighting or high background noise, (4) Switching tabs or staying idle may restart the video. Fix: stay on ViBe tab, keep camera on, watch in quiet well-lit environment.', tags: ['vibe', 'video stuck', 'repeating', 'looping', 'camera', 'proctoring'], keywords: ['video stuck', 'repeating', 'loop', 'vibe', 'restart', 'camera'], importance: 'critical', verified: true, source: 'official' },
  { category: 'ViBe', sectionId: '12.4', question: 'Can I use a mobile or tablet for ViBe?', answer: 'No, only desktop/laptop is supported on ViBe.', tags: ['vibe', 'mobile', 'tablet', 'device'], keywords: ['mobile', 'tablet', 'phone', 'device', 'vibe'], importance: 'medium', verified: true, source: 'official' },
  { category: 'ViBe', sectionId: '12.6', question: 'I completed all ViBe videos and quizzes but my progress shows less than 100%. What should I do?', answer: 'Do not worry. This may be due to a penalty score causing a missed item. Verify you have completed ALL course items (1006/1006). If not, retry missed content. Try: refresh browser, log out and clear cache, log back in. If issue persists after all items done, contact Yaksha with #escalate-ViBe.', tags: ['vibe', 'progress', '100%', 'not complete', 'bug'], keywords: ['progress', '100 percent', 'not complete', 'vibe', 'less than'], importance: 'high', verified: true, source: 'official' },
  { category: 'ViBe', sectionId: '12.7', question: 'Can I request an exception or bypass ViBe? I am unhappy with the platform.', answer: 'ViBe is open-source and built by interns. If you strongly feel ViBe doesn\'t reflect your understanding, there is a formal alternative: 3-hour proctored exam with two cameras and a live human proctor. Scoring: below 60% = must rejoin next cohort. 60-80% = one more chance. Above 80% = pass. This exam is held fortnightly — much slower than just completing ViBe normally.', tags: ['vibe', 'bypass', 'exception', 'unhappy', 'alternative', 'exam'], keywords: ['bypass vibe', 'exception', 'alternative exam', 'unhappy', 'skip'], importance: 'medium', verified: true, source: 'official' },
  { category: 'ViBe', sectionId: '12.8', question: 'Is the ViBe consent form compulsory? What if I don\'t want to give camera access?', answer: 'Yes — the consent form is compulsory. Providing consent is mandatory for anyone enrolling in a ViBe course. The platform requires webcam and microphone access throughout learning for proctoring. If you choose not to grant access, you will not be able to proceed. ViBe does NOT continuously record videos — it uses real-time monitoring only.', tags: ['vibe', 'consent', 'camera', 'mandatory', 'proctoring'], keywords: ['consent', 'camera access', 'compulsory', 'mandatory', 'vibe'], importance: 'high', verified: true, source: 'official' },
  { category: 'ViBe', sectionId: '12.9', question: 'What are penalty scores on ViBe and how do they affect HP?', answer: 'Penalty scores are generated when anomalies are detected during ViBe activity (irregular behavior during videos or quizzes). High penalty scores may require you to rewatch video and retake quiz. Currently penalty scores do NOT impact your HP or overall performance evaluation — their primary purpose is to ensure genuine engagement.', tags: ['vibe', 'penalty', 'hp', 'health points', 'anomaly'], keywords: ['penalty score', 'hp', 'health points', 'affect', 'vibe'], importance: 'high', verified: true, source: 'official' },
  { category: 'ViBe', sectionId: '12.11', question: 'What is Linear Progression on ViBe?', answer: 'Linear progression is enabled for every ViBe course. You must watch videos and attempt quizzes in the EXACT order they appear on the left panel. You cannot click on a video or quiz far ahead. You must complete each item before the next one unlocks. Skipping videos or quizzes is not allowed by design.', tags: ['vibe', 'linear progression', 'order', 'sequence', 'locked'], keywords: ['linear progression', 'order', 'sequence', 'locked', 'vibe'], importance: 'critical', verified: true, source: 'official' },
  { category: 'ViBe', sectionId: '12.12', question: 'Can I use the left navigation panel to jump ahead on ViBe?', answer: 'No. The left navigation panel is a PROGRESS MAP only, not a jump-to menu. Instead of clicking left panel, use the "Next Quiz" or "Next Lesson" button on the right panel. Trying to skip ahead through the left panel triggers the "Access Restricted" alert.', tags: ['vibe', 'navigation', 'jump', 'skip', 'left panel'], keywords: ['left panel', 'navigation', 'jump ahead', 'skip', 'vibe'], importance: 'high', verified: true, source: 'official' },
  { category: 'ViBe', sectionId: '12.13', question: 'I am seeing a red "Access Restricted" banner on ViBe. Is this a bug?', answer: 'No, it is NOT a bug. The red "Access Restricted" banner is intentional. It appears when you try to open an item before completing all items that come before it. ViBe automatically returns you to the previous valid content. You will not lose progress — it\'s the system telling you there\'s something earlier you haven\'t finished.', tags: ['vibe', 'access restricted', 'red banner', 'bug', 'error'], keywords: ['access restricted', 'red banner', 'bug', 'error', 'vibe'], importance: 'critical', verified: true, source: 'official' },
  { category: 'ViBe', sectionId: '12.14', question: 'How do I resolve the Access Restricted error on ViBe?', answer: 'Steps: (1) Go to left panel, scroll from beginning, (2) Look for any item WITHOUT a completion tick, (3) Complete that item (watch full video or submit quiz), (4) Refresh page. If still showing after all items done, contact Yaksha with #escalate-ViBe. In most cases, finding and completing the missed item clears the alert.', tags: ['vibe', 'access restricted', 'fix', 'resolve', 'missed item'], keywords: ['resolve access restricted', 'fix', 'missed item', 'vibe'], importance: 'high', verified: true, source: 'official' },
  { category: 'ViBe', sectionId: '12.20', question: 'What is the most common avoidable mistake on ViBe?', answer: 'Sitting with a window directly behind you during the day. Your camera only sees a dark silhouette — the helper struggles to confirm your presence and the lesson may pause or rewind. Fix: move so the window is to your side or in front of the laptop. A lamp placed in front of you works well in the evening.', tags: ['vibe', 'common mistake', 'lighting', 'window', 'camera'], keywords: ['common mistake', 'lighting', 'window behind', 'silhouette', 'vibe'], importance: 'high', verified: true, source: 'official' },
  { category: 'ViBe', sectionId: '12.21', question: 'Why does the ViBe lesson keep pausing or restarting even when I\'m paying attention?', answer: 'Usually a small environmental issue, not the platform. Checklist: (1) Face too dark → add lamp in front, (2) Face partly out of frame → raise laptop or sit closer, (3) Background voices → close door or move to quiet room, (4) Switched tabs or went idle → stay on ViBe tab, take breaks BETWEEN clips not during, (5) Camera/mic permission dropped → check browser lock icon.', tags: ['vibe', 'pausing', 'restarting', 'environment', 'lighting'], keywords: ['pausing', 'restarting', 'lesson stops', 'vibe', 'troubleshoot'], importance: 'high', verified: true, source: 'official' },
  { category: 'ViBe', sectionId: '12.24', question: 'Will I lose ViBe progress if I clear my browser or reinstall it?', answer: 'No. Your progress is saved on the server, tied to your registered email — not on your browser. Refreshing, clearing cache, switching browsers, or reinstalling will not wipe progress. When in doubt: log out, log back in with the same registered email.', tags: ['vibe', 'progress', 'clear browser', 'cache', 'lost'], keywords: ['lose progress', 'clear browser', 'cache', 'reinstall', 'vibe'], importance: 'medium', verified: true, source: 'official' },
  // ROSETTA
  { category: 'Rosetta', sectionId: '9.1', question: 'What is Rosetta?', answer: 'Rosetta is your internship journal — a 65-day document, one entry per day, every day, for the full duration of Summership 2026. You write in it daily, keep it privately, and submit it at the end as one of your completion requirements. Named after the Rosetta Stone — consistency and honesty will become your key to understanding your own experience.', tags: ['rosetta', 'journal', 'daily', 'reflection', '65 days'], keywords: ['rosetta', 'journal', 'what is', 'daily writing', 'reflection'], importance: 'high', verified: true, source: 'official' },
  { category: 'Rosetta', sectionId: '9.3', question: 'What is a "thinking routine" in Rosetta?', answer: 'Each day in Rosetta has a thinking routine — a short framework giving your reflection a specific shape. Examples: 3-2-1 (3 things engaged with, 2 questions, 1 surprise), Muddy/Clear (what is sharp vs foggy), What/So What/Now What (facts → meaning → action). Routines rotate across 65 days so the journal doesn\'t feel repetitive.', tags: ['rosetta', 'thinking routine', 'reflection', '3-2-1', 'muddy clear'], keywords: ['thinking routine', 'rosetta', 'prompt', 'muddy clear', 'reflection'], importance: 'medium', verified: true, source: 'official' },
  { category: 'Rosetta', sectionId: '9.7', question: 'What is the one rule for Rosetta journal?', answer: 'Write what is true. Not what sounds impressive. Not what you think we want to read. If you hated today, write that. If you\'re confused and frustrated, write that. Honest, specific entries only. We will know immediately if an entry reads like an LLM wrote it. Do not use AI for Rosetta.', tags: ['rosetta', 'rule', 'honest', 'true', 'one rule'], keywords: ['rosetta rule', 'honest', 'true', 'only rule', 'requirement'], importance: 'critical', verified: true, source: 'official' },
  { category: 'Rosetta', sectionId: '9.8', question: 'Can I use ChatGPT or AI tools to write my Rosetta journal entries?', answer: 'No. This is the one firm rule of Rosetta. The journal records your thinking, not an AI\'s output. Entries that read as AI-generated will not be counted toward your completion requirement. If your entire journal reads this way, it will not be accepted. AI tools are for technical work where permitted — not for Rosetta.', tags: ['rosetta', 'chatgpt', 'ai', 'prohibited', 'not allowed'], keywords: ['chatgpt rosetta', 'ai journal', 'prohibited', 'not allowed', 'rosetta'], importance: 'critical', verified: true, source: 'official' },
  { category: 'Rosetta', sectionId: '9.9', question: 'What if I miss a day in my Rosetta journal?', answer: 'Fill it in as soon as you can. Write the ACTUAL date you are filling it in, not the date of the missed entry. Be honest in the entry about writing it late and why. Do not leave entries blank. A late honest entry is always better than no entry. If you consistently miss entries, something else may be going wrong — use Yaksha chat.', tags: ['rosetta', 'miss', 'late', 'skip', 'blank'], keywords: ['miss day', 'late entry', 'skip', 'rosetta', 'forgot'], importance: 'medium', verified: true, source: 'official' },
  // TEAM FORMATION
  { category: 'Team Formation', sectionId: '13.1', question: 'Is team formation compulsory in VINS?', answer: 'Yes. All projects in Phase 2 and Phase 3 (some parts) must be completed in teams. Every participant is required to be part of a team.', tags: ['team', 'compulsory', 'phase 2', 'required'], keywords: ['team compulsory', 'required', 'team formation', 'mandatory'], importance: 'high', verified: true, source: 'official' },
  { category: 'Team Formation', sectionId: '13.2', question: 'What is the team size?', answer: 'The team size is fixed at FOUR members. This is mandatory — you cannot have fewer or more members at the time of final formation. Teams with fewer than 4 will be expanded by admin.', tags: ['team', 'size', 'four', 'members', 'fixed'], keywords: ['team size', 'how many', 'members', 'four', 'fixed'], importance: 'high', verified: true, source: 'official' },
  { category: 'Team Formation', sectionId: '13.3', question: 'How are teams formed?', answer: 'For students who joined on May 15-16: Teams were formed through a structured activity. For students joining later: Teams will be randomly assigned by the administration. You cannot form your own team if you start later.', tags: ['team', 'formed', 'random', 'activity', 'assigned'], keywords: ['team formed', 'how teams', 'random', 'assigned', 'activity'], importance: 'high', verified: true, source: 'official' },
  { category: 'Team Formation', sectionId: '13.8', question: 'Can I form a team with someone from my own college?', answer: 'No. Teams must consist of members from DIFFERENT institutions to encourage networking. Exception: Students from the same institution but different campuses/locations may be allowed.', tags: ['team', 'same college', 'different', 'institution', 'networking'], keywords: ['same college', 'own college', 'team', 'institution'], importance: 'medium', verified: true, source: 'official' },
  { category: 'Team Formation', sectionId: '13.16', question: 'We selected Project X but were assigned Project Y. Can we change it?', answer: 'No. Project assignments are final and cannot be changed. Allocation is done to ensure balanced distribution across projects. Your team must proceed with the assigned project.', tags: ['project', 'assignment', 'change', 'preference', 'final'], keywords: ['change project', 'wrong project', 'reassign', 'project assignment'], importance: 'medium', verified: true, source: 'official' },
  { category: 'Team Formation', sectionId: '13.23', question: 'How will communication happen within teams?', answer: 'Teams are expected to self-organize internal coordination (e.g., a small WhatsApp/email thread limited to the four teammates). Official programme updates come via email and Yaksha chat on samagama.in. Note: a 4-person team thread for project work is fine — what\'s prohibited is any group purporting to act on behalf of Vicharanashala or the wider cohort (see §6.1).', tags: ['team', 'communication', 'whatsapp', 'coordinate', 'group'], keywords: ['team communication', 'coordinate', 'whatsapp team', 'how communicate'], importance: 'medium', verified: true, source: 'official' },
  // CERTIFICATE
  { category: 'Certificate', sectionId: '4.4', question: 'Will I get a certificate from Vicharanashala?', answer: 'Yes — every intern who COMPLETES the internship gets a certificate from Vicharanashala, IIT Ropar. The internship is demanding — candidates who drop out mid-way do not get a certificate. Finishing means something because the bar is high.', tags: ['certificate', 'completion', 'iit ropar', 'finish'], keywords: ['certificate', 'get certificate', 'completion', 'iit ropar'], importance: 'high', verified: true, source: 'official' },
  { category: 'Certificate', sectionId: '8.2', question: 'Does the certificate specify online or offline mode?', answer: 'No. The certificate issued upon completion is the same for both tracks. It is issued by Vicharanashala, IIT Ropar, and does not specify whether you completed it online or on campus. The mode is not called out on the document.', tags: ['certificate', 'online', 'offline', 'mode', 'same'], keywords: ['certificate online offline', 'mode', 'specify', 'difference'], importance: 'medium', verified: true, source: 'official' },
  { category: 'Certificate', sectionId: '8.3', question: 'Will the certificate be a physical copy or e-certificate?', answer: 'The completion certificate is issued as an e-certificate — you download it from your dashboard on samagama.in after completing Bronze and Silver. We do not print and mail physical copies. The certificate is digitally signed and can be verified from our database using the certificate number.', tags: ['certificate', 'e-certificate', 'digital', 'physical', 'download'], keywords: ['physical certificate', 'e-certificate', 'digital', 'hardcopy'], importance: 'medium', verified: true, source: 'official' },
  // COMMUNICATION
  { category: 'AI/Yaksha', sectionId: '6.1', question: 'Are unofficial WhatsApp groups or Telegram channels allowed?', answer: 'NO — unofficial channels of any kind are strictly prohibited. All communication must flow through: (1) Yaksha chat on samagama.in (#escalate for human), (2) Email from no-reply@vicharanashala.ai (outbound only), (3) The moderated WhatsApp troubleshooting group (invited after offer letter). Candidates found running unofficial groups face withdrawal, blacklisting, and college notification.', tags: ['whatsapp', 'telegram', 'unofficial', 'prohibited', 'group'], keywords: ['whatsapp group', 'unofficial', 'telegram', 'allowed', 'prohibited'], importance: 'critical', verified: true, source: 'official' },
  { category: 'AI/Yaksha', sectionId: '11.1', question: 'I cannot type in the Yaksha chat. What should I do?', answer: 'After logging into your Yaksha portal, if you can\'t type in the field, scroll up to the TOP of your window and click on the "Chat with Yaksha" button to activate Yaksha. This will enable you to interact properly.', tags: ['yaksha', 'chat', 'cannot type', 'bug', 'fix'], keywords: ['yaksha chat', 'cannot type', 'activate', 'interact', 'fix'], importance: 'medium', verified: true, source: 'official' },
  // COURSEWORK
  { category: 'Coursework', sectionId: '10.1', question: 'I previously interned with VLED. Am I exempt from any coursework?', answer: 'Partially. If you previously interned with VLED and completed MERN Stack coursework, you don\'t need to repeat it. Type #exemption from mern stack course in Yaksha chat. However, the AI Fundamentals course is NEW this cycle and mandatory for everyone including returning interns.', tags: ['exemption', 'vled', 'mern', 'returning', 'coursework'], keywords: ['exemption', 'vled', 'returning intern', 'mern exemption', 'previous'], importance: 'medium', verified: true, source: 'official' },
  { category: 'Coursework', sectionId: '10.4', question: 'Are live sessions mandatory?', answer: 'Yes — live sessions are mandatory for EVERY intern, regardless of path (coursework track, MERN-exempt, or viva route). The exchange of knowledge across the cohort — diverse streams, varying experience levels — cannot be replicated by self-paced study.', tags: ['live sessions', 'mandatory', 'attendance', 'viva', 'compulsory'], keywords: ['live session', 'mandatory', 'compulsory', 'attend', 'required'], importance: 'high', verified: true, source: 'official' },
  // GENERAL
  { category: 'General', sectionId: '5.1', question: 'What will I work on during the internship?', answer: 'A real open-source project from Vicharanashala\'s portfolio — assigned based on your background and the lab\'s current needs. Areas include: AI/ML, web development, NLP, computer vision, agriculture-tech (Annam.AI), education-tech (ViBe), and open-source infrastructure. The exact problem is not pre-published.', tags: ['work', 'project', 'open source', 'assignment', 'areas'], keywords: ['what work on', 'project', 'open source', 'assignment', 'area'], importance: 'high', verified: true, source: 'official' },
  { category: 'General', sectionId: '5.4', question: 'Is there a stipend in VINS?', answer: 'No. The internship is unpaid. Stellar performers MAY be recognised with a discretionary stipend at the lab\'s option, but this is not promised or expected. Do not plan or budget around receiving a stipend.', tags: ['stipend', 'paid', 'unpaid', 'salary', 'compensation'], keywords: ['stipend', 'paid', 'salary', 'money', 'compensation'], importance: 'high', verified: true, source: 'official' },
  { category: 'General', sectionId: '5.5', question: 'Do I need my own laptop? What software should I preload?', answer: 'Yes — a personal laptop is required. Prefer Linux or macOS. If using Windows, install WSL (Windows Subsystem for Linux) or PuTTY for SSH. You will be SSH-ing into machines. No fixed software-preload list — your mentor will guide you once your project is assigned.', tags: ['laptop', 'software', 'linux', 'macos', 'windows', 'wsl'], keywords: ['laptop', 'software', 'preload', 'linux', 'windows', 'requirement'], importance: 'medium', verified: true, source: 'official' },
  { category: 'General', sectionId: '5.7', question: 'Why hasn\'t my mentor been assigned yet?', answer: 'Mentors are NOT assigned on day 1. You will be assigned a mentor when you move to the project phase (after Bronze coursework). Before that, complete the mandatory Bronze phase coursework first. There is no Discord server — communication is through Yaksha chat on samagama.in only.', tags: ['mentor', 'not assigned', 'day 1', 'when', 'assignment'], keywords: ['mentor not assigned', 'when mentor', 'day 1', 'assignment'], importance: 'high', verified: true, source: 'official' },
  { category: 'General', sectionId: '9.14', question: 'My college requires written confirmation that the internship is self-paced. What document can I share?', answer: 'This is NOT a self-paced internship — it is a very rigorous, time-demanding programme. It is not permitted to be part of any other activity during this period. You cannot share a document saying it is self-paced because it is not.', tags: ['self-paced', 'confirmation', 'college', 'rigorous', 'not self-paced'], keywords: ['self paced', 'flexible', 'confirmation', 'college letter', 'schedule'], importance: 'high', verified: true, source: 'official' }
];

async function seedFAQ() {
  try {
    await mongoose.connect(process.env.MONGODB_URI);
    console.log('✅ Connected to MongoDB');

    const existing = await FAQ.countDocuments();
    if (existing > 0) {
      console.log(`⚠️  ${existing} FAQs already exist. Dropping and re-seeding...`);
      await FAQ.deleteMany({});
    }

    const result = await FAQ.insertMany(faqs);
    console.log(`✅ Seeded ${result.length} FAQs successfully!`);

    // Show categories
    const cats = [...new Set(faqs.map(f => f.category))];
    console.log('📚 Categories:', cats.join(', '));

    await mongoose.disconnect();
    console.log('✅ Done!');
  } catch (err) {
    console.error('❌ Seed error:', err.message);
    process.exit(1);
  }
}

seedFAQ();
